"use client";
import { Button } from '@/components/ui/button';
import { ChevronDownIcon, ExternalLinkIcon, GitHubLogoIcon } from '@radix-ui/react-icons';
// import { initDash } from '@/lib/server-utils';
import { ProjectConfigProvider } from '@/providers/projectDataProvider';
// import type { Metadata } from 'next'
import Sidebar from '@/components/sideBar';

// export const metadata: Metadata = {
//     title: 'computeflow',
//     description: 'Generated by create next app',
// }

export default function ProjectDashLayout({ params, children }: { params: { project: string }, children: React.ReactNode }) {

    const project = {
        commands: {
            rootDir: '',
            startCommand: 'index.js',
            buildCommands: 'npm install'
        },
        deployed_from: 'https://github.com/Axnjr/starter-express-api',
        env_variables: '',
        id: 'rec_cq3coc82kjje0ecqdbvg',
        instance_metadata: { instanceId: 'i-0c354a655d3d33149', instanceType: 'Plus' },
        ip: '65.1.106.41',
        project_name: 'Rdev Proxy Server',
        region: 'virginia',
        runtime: 'nodejs',
        status: 'under_deployment',
        user: { id: 'ceec7305-9bc9-4dc7-96fd-fcfac4dff166' },
        xata: {
            createdAt: "2024-07-04T16:22:09.135Z",
            updatedAt: "2024-07-04T16:22:10.505Z",
            version: 1
        }
    } // await initDash(params)
    // console.log("Layout was rendered !!", project)

    return (
        <html lang='en'>
            <body className='h-fit w-full dark:bg-black bg-white dark:text-white text-black pb-12'>
                <Sidebar />
                <div className='ml-[16.666667%] w-[83.334%] '>
                    <div className="py-8 px-8 flex items-center justify-between">
                        <div className='text-xs'>
                            <h1 className="text-4xl tracking-tight font-bold">
                                {project?.project_name.replaceAll("-", " ")}
                            </h1>
                            <div className="flex items-center mt-2">
                                <a href={project?.deployed_from} className='flex items-center underline font-medium'>
                                    {project.project_name.replaceAll(" ","").toLowerCase()}.computeflow.dev
                                    <ExternalLinkIcon className="mr-1 size-3" />
                                </a>
                                {/* <span className='mx-1 text-xl'>·</span>
                                <p className='capitalize px-2 py-1 bg-sky-500/20 text-sky-500 rounded-full'>{project.region}</p> */}
                            </div>
                            {/* <p className='capitalize mt-2 w-fit px-2 py-1 bg-fuchsia-500/20 text-fuchsia-500 rounded-full'>
                                4 vcpu · 16 GB - {project.instance_metadata.instanceType} Compute Type
                            </p> */}
                        </div>
                        <div className="flex space-x-2">
                            <Button>{
                                project?.deployed_from.includes("github")
                                    ?
                                    <a className="flex items-center" href={project?.deployed_from}><GitHubLogoIcon className="mr-2 -ml-1" /> Repository</a>
                                    :
                                    <a className="flex items-center" href={"https://" + project?.deployed_from + ".cheapcloud.dev"}>
                                        <svg className='mr-2 -ml-1 inline-block' xmlns="http://www.w3.org/2000/svg" width="19" height="15" viewBox="0 0 23 18" fill="none">
                                            <path fill="#0DB7ED" d="M22.338 5.987c-.066-.044-.616-.473-1.804-.473-.308 0-.616.033-.924.088-.231-1.54-1.518-2.32-1.573-2.354l-.32-.187-.197.297a3.636 3.636 0 0 0-.561 1.31c-.22.88-.088 1.715.363 2.43-.54.308-1.42.385-1.606.385H1.229a.688.688 0 0 0-.682.693c0 1.265.198 2.53.638 3.718.495 1.31 1.243 2.277 2.2 2.871 1.078.66 2.849 1.034 4.862 1.034a14.7 14.7 0 0 0 2.662-.242c1.232-.22 2.42-.649 3.509-1.276a9.13 9.13 0 0 0 2.387-1.969c1.155-1.287 1.837-2.75 2.332-4.015h.209c1.254 0 2.035-.506 2.464-.935.286-.264.495-.583.649-.957l.088-.264-.21-.154ZM2.582 7.077h1.936a.18.18 0 0 0 .176-.177V5.162a.18.18 0 0 0-.176-.176H2.582a.174.174 0 0 0-.176.176V6.9c.01.1.077.176.176.176Zm2.673 0H7.19a.18.18 0 0 0 .176-.177V5.162a.18.18 0 0 0-.176-.176H5.255a.174.174 0 0 0-.176.176V6.9c.01.1.077.176.176.176Zm2.717 0h1.925c.11 0 .187-.078.187-.177V5.162c0-.088-.066-.176-.187-.176H7.972c-.088 0-.165.077-.165.176V6.9c0 .1.066.176.165.176Zm2.684 0h1.947c.088 0 .165-.078.165-.177V5.162c0-.088-.066-.176-.165-.176h-1.947c-.088 0-.165.077-.165.176V6.9c0 .1.077.176.165.176ZM5.255 4.611H7.19c.088 0 .176-.099.176-.198V2.687a.174.174 0 0 0-.176-.176H5.255c-.1 0-.176.066-.176.176v1.727c.01.1.077.198.176.198Zm2.717 0h1.925c.11 0 .187-.099.187-.198V2.687c0-.099-.066-.176-.187-.176H7.972c-.088 0-.165.066-.165.176v1.727c0 .1.066.198.165.198Zm2.684 0h1.947c.088 0 .165-.099.165-.198V2.687c0-.099-.077-.176-.165-.176h-1.947c-.088 0-.165.066-.165.176v1.727c0 .1.077.198.165.198Zm0-2.508h1.947c.088 0 .165-.077.165-.176V.212c0-.11-.077-.187-.165-.187h-1.947c-.088 0-.165.066-.165.187v1.716c0 .088.077.176.165.176Zm2.706 4.972h1.936a.174.174 0 0 0 .176-.176V5.162a.18.18 0 0 0-.176-.176h-1.936c-.088 0-.165.077-.165.176V6.9c0 .1.077.176.165.176Z"></path>
                                        </svg>
                                        Docker Hub
                                    </a>
                            }</Button>
                            <Button variant="outline">Deployments <ChevronDownIcon className='ml-2' /></Button>
                        </div>
                    </div>
                    <div className='flex items-center justify-between px-8 py-4 mb-4'>
                        <div>
                            <p className='text-xs uppercase text-neutral-500'>Status</p>
                            <h1 className='text-base font-bold'>{project.status}</h1>
                        </div>
                        <div>
                            <p className='text-xs uppercase text-neutral-500'>Region</p>
                            <h1 className='text-base font-bold'>{project.region}</h1>
                        </div>
                        <div>
                            <p className='text-xs uppercase text-neutral-500'>CPU Cores</p>
                            <h1 className='text-base font-bold'>4</h1>
                        </div>
                        <div>
                            <p className='text-xs uppercase text-neutral-500'>RAM</p>
                            <h1 className='text-base font-bold'>16</h1>
                        </div>
                        <div>
                            <p className='text-xs uppercase text-neutral-500'>Type</p>
                            <h1 className='text-base font-bold'>{project.instance_metadata.instanceType}</h1>
                        </div>
                    </div>
                    <ProjectConfigProvider value={JSON.stringify(project)}>
                        {children}
                    </ProjectConfigProvider>
                </div>
            </body>
        </html>
    )
}