import AllProvider from '@/providers/AuthProvider'
import type { Metadata } from 'next'
import "./globals.css"
import Nav from '../components/nav'
import { Inter } from "next/font/google";

export const metadata: Metadata = {
	title: 'computeflow',
	description: 'Generated by create next app',
}

// const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<AllProvider>
				<body>
					<Nav/>
					{children}
				</body>
			</AllProvider>
		</html>
	)
}