import AllProvider from '@/providers/AuthProvider'
import type { Metadata } from 'next'
import "./globals.css"

export const metadata: Metadata = {
	title: 'Ignition - Ultimate real time platform',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

	// const data = await serverClient.getData()
  	// const dataSet = await serverClient.setData("test-data trpc working in sever component")

	return (
		<html lang="en">
			<AllProvider>
				<body>
					{/* <Nav/> */}
					{children}
				</body>
			</AllProvider>
		</html>
	)
}