// Generated by Xata Codegen 0.29.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
	BaseClientOptions,
	SchemaInference,
	XataRecord,
} from "@xata.io/client";

const tables = [
	{
		name: "nextauth_users",
		columns: [
			{ name: "email", type: "email" },
			{ name: "emailVerified", type: "datetime" },
			{ name: "name", type: "string" },
			{ name: "image", type: "string" },
		],
	},
	{
		name: "nextauth_accounts",
		columns: [
			{ name: "user", type: "link", link: { table: "nextauth_users" } },
			{ name: "type", type: "string" },
			{ name: "provider", type: "string" },
			{ name: "providerAccountId", type: "string" },
			{ name: "refresh_token", type: "string" },
			{ name: "access_token", type: "string" },
			{ name: "expires_at", type: "int" },
			{ name: "token_type", type: "string" },
			{ name: "scope", type: "string" },
			{ name: "id_token", type: "text" },
			{ name: "session_state", type: "string" },
		],
	},
	{
		name: "nextauth_verificationTokens",
		columns: [
			{ name: "identifier", type: "string" },
			{ name: "token", type: "string" },
			{ name: "expires", type: "datetime" },
		],
	},
	{
		name: "nextauth_users_accounts",
		columns: [
			{ name: "user", type: "link", link: { table: "nextauth_users" } },
			{ name: "account", type: "link", link: { table: "nextauth_accounts" } },
		],
	},
	{
		name: "nextauth_users_sessions",
		columns: [
			{ name: "user", type: "link", link: { table: "nextauth_users" } },
			{ name: "session", type: "link", link: { table: "nextauth_sessions" } },
		],
	},
	{
		name: "nextauth_sessions",
		columns: [
			{ name: "sessionToken", type: "string" },
			{ name: "expires", type: "datetime" },
			{ name: "user", type: "link", link: { table: "nextauth_users" } },
		],
	},
	{
		name: "todos",
		columns: [
			{ name: "message", type: "string" },
			{
				name: "createdAt",
				type: "datetime",
				notNull: true,
				defaultValue: "now",
			},
			{ name: "done", type: "bool", notNull: true, defaultValue: "false" },
			{ name: "author", type: "link", link: { table: "nextauth_users" } },
		],
	},
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type DatabaseSchema = {};

const DatabaseClient = buildClient();

const defaultOptions = {
	databaseURL:
		"https://yakshit-chhipa-s-workspace-p8bvk5.eu-central-1.xata.sh/db/cheapcloud",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
	constructor(options?: BaseClientOptions) {
		super({ ...defaultOptions, ...options }, tables);
	}
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
	if (instance) return instance;

	instance = new XataClient();
	return instance;
};
